routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('send-mail', function () {

    $details = [
        'title' => 'Mail from Lufa Intégrateur',
        'body' => 'This is for testing email using mailjet'
    ];

    \Mail::to('mokhouthioune96@gmail.com')->send(new \App\Mail\MyTestMail($details));

    dd("Email is Sent.");
});

Auth::routes();

Route::get('/', function () {
    //return View::make('welcome');
    return View::make('auth.login');
})->name('welcome');

Route::post('/login', [App\Http\Controllers\Auth\LoginController::class, 'override_login'])->name('override.login');
Route::post('/register', [App\Http\Controllers\Auth\RegisterController::class, 'override_register'])->name('override.register');
Route::post('/register/step', [App\Http\Controllers\Auth\RegisterController::class, 'register_step'])->name('register.step');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->middleware('auth')->name('home');
Route::get('/home-admin', [App\Http\Controllers\HomeController::class, 'homeAdmin'])->middleware('auth')->middleware('cabinet')->name('homeAdmin');

Route::resource('users', App\Http\Controllers\UserController::class)->middleware('isAdmin')->middleware('auth');
Route::get('/user/detail/{id}', [App\Http\Controllers\UserController::class, 'show_override'])->middleware('isAdmin')->middleware('auth')->name('users.detail');
Route::get('/user/profiling/{id}', [App\Http\Controllers\UserController::class, 'profiling'])->middleware('isAdmin')->middleware('auth')->name('users.profiling');
Route::post('/user/notation', [App\Http\Controllers\UserController::class, 'notation'])->middleware('isAdmin')->middleware('auth')->name('users.notation');

Route::resource('roles', App\Http\Controllers\RoleController::class)->middleware('isAdmin')->middleware('auth');
Route::resource('addresses', App\Http\Controllers\AddressController::class)->middleware('isAdmin')->middleware('auth');
Route::resource('transactions', App\Http\Controllers\TransactionController::class)->middleware('isAdmin')->middleware('auth');
Route::resource('clients', App\Http\Controllers\ClientController::class)->middleware('isAdmin')->middleware('auth');

Route::resource('members', App\Http\Controllers\MemberController::class)->middleware('auth');
Route::get('/member/{id}', [App\Http\Controllers\MemberController::class, 'indexOth'])->middleware('isAdmin')->middleware('auth')->name('members.team.index');
Route::get('/member/create/{id}', [App\Http\Controllers\MemberController::class, 'createOth'])->middleware('isAdmin')->middleware('auth')->name('members.team.create');

Route::resource('opportunities', App\Http\Controllers\OpportunityController::class)->middleware('cabinet')->middleware('auth');
Route::get('/opportunities/share/{id}', [App\Http\Controllers\OpportunityController::class, 'share'])->middleware('cabinet')->middleware('auth')->name('opportunities.share');
Route::post('/opportunities/scheduled', [App\Http\Controllers\OpportunityController::class, 'isScheduled'])->middleware('cabinet')->middleware('auth')->name('opportunities.scheduled');

Route::resource('missions', App\Http\Controllers\MissionController::class)->middleware('cabinet')->middleware('auth');
Route::post('missions/store/coach', [App\Http\Controllers\MissionController::class, 'store_coach'])->middleware('auth')->name('missions.store.coach');
Route::get('missions/details/{id}', [App\Http\Controllers\MissionController::class, 'show_override'])->middleware('auth')->name('missions.details');
Route::get('evaluation/{id}', [App\Http\Controllers\MissionController::class, 'evaluation'])->middleware('cabinet')->middleware('auth')->name('mission.evaluation');

Route::resource('livrables', App\Http\Controllers\LivrableController::class);
Route::get('livrables/mission/{id}', [App\Http\Controllers\LivrableController::class, 'index_override'])->middleware('auth')->name('livrable.index');
Route::get('livrable/{id}', [App\Http\Controllers\LivrableController::class, 'create_override'])->middleware('auth')->name('livrable.create');
Route::post('launch/livrable', [App\Http\Controllers\LivrableController::class, 'launch'])->middleware('auth')->middleware('cabinet')->name('livrable.launch');
Route::get('details_livrable/{id}', [App\Http\Controllers\LivrableController::class, 'details_livrable'])->middleware('auth')->name('details_livrable');
Route::patch('soummetre/livrable/{id}', [App\Http\Controllers\LivrableController::class, 'soummetre'])->middleware('auth')->name('livrable.soummetre');
Route::post('valider/livrable/{id}', [App\Http\Controllers\LivrableController::class, 'valider'])->middleware('cabinet')->middleware('auth')->name('livrable.valider');
Route::post('validation/livrable', [App\Http\Controllers\LivrableController::class, 'validation'])->middleware('cabinet')->middleware('auth')->name('livrable.validation');

Route::get('messages', [App\Http\Controllers\ContactController::class, 'mes_messages'])->middleware('auth')->name('messages.index');
Route::post('store_messages', [App\Http\Controllers\ContactController::class, 'store_messages'])->middleware('auth')->name('store_messages');
Route::get('messages/{id}', [App\Http\Controllers\ContactController::class, 'show_messages'])->middleware('auth')->name('messages.show');

Route::get('/calendrier-mission', function () {
    return View::make('missions.calendrier');
});

Route::get('/admin/calendrier-excution-empty', function () {
    return View::make('livrables.calendrier-add');
});
Route::get('/admin/calendrier-excution', function () {
    return View::make('admin.calendrier-excution');
});

Route::get('/register/step/5', function () {
    return View::make('auth.register-step-5');
});

// Route::get('/admin/gestion-opportinute', function () {
//     return View::make('admin.gestion-opportinute');
// });
// Route::get('/admin/creer-une-opportinute', function () {
//     return View::make('admin.creer-une-opportinute');
// });
// Route::get('/admin/attribution-opportunite', function () {
//     return View::make('admin.attribution-opportunite');
// });

// Route::resource('files', App\Http\Controllers\FileController::class);
// Route::resource('categories', App\Http\Controllers\CategoryController::class);
// Route::resource('categorieCoaches', App\Http\Controllers\CategorieCoachController::class);

app/Models/Livrable.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class Livrable
 * @package App\Models
 * @version August 1, 2023, 5:41 pm UTC
 *
 * @property string $libelle
 * @property string $deadline
 * @property int $file_id
 */
class Livrable extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'livrables';
    
    protected $dates = ['deleted_at'];

    public $fillable = [
        'libelle',
        'deadline',
        'statut',
        'template_file_id',
        'execution_file_id',
        'opportunity_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'libelle' => 'string',
        'deadline' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'libelle' => 'required',
        'deadline' => 'required',
        'template_file_id' => 'required',
        'opportunity_id' => 'required'
    ];

    
}

app/Http/Controllers/LivrableController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateLivrableRequest;
use App\Http\Requests\UpdateLivrableRequest;
use App\Http\Controllers\AppBaseController;
use App\Models\Livrable;
use App\Models\Opportunity;
use App\Models\Member;
use App\Models\Mission;
use Illuminate\Http\Request;
use App\Models\Client;
use App\Models\User;
use App\Models\File;
use App\Mail\Soumettre;
use App\Mail\AccepterRefuser;
use App\Mail\ClotureMission;

use Mail;
use DB;
use Flash;
use Response;
use Carbon\Carbon;
use Illuminate\Support\Str;
use Auth;

class LivrableController extends AppBaseController
{
    /**
     * Display a listing of the Livrable.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        /** @var Livrable $livrables */
        $livrables = Livrable::all();

        return view('livrables.index')
            ->with('livrables', $livrables);
    }

    public function index_override($id)
    {
        /** @var Opportunity $opportunity */
        $opportunity = Opportunity::find($id);
        if (empty($opportunity)) {
            Flash::error('Opportunité non trouvée !');
            return redirect(route('opportunities.index'));
        }
    
        //Misson status 
        $mission_status = Mission::where('opportunity_id', $opportunity->id)->where('status', 'Accepté')->first() ? true : false;

        /** @var Livrable $livrables */
        $livrables = Livrable::where('opportunity_id', $opportunity->id)->get();

        //days livrable
        $sum_days_livrable = Livrable::where('opportunity_id', $opportunity->id)->sum('deadline');

        //Livrables
        $etat_formulaire = true;
        $etat_formulaire = (empty($livrables)) ? false : true;
        foreach ($livrables as $livrable) 
            if($livrable->statut != 2){
                $etat_formulaire = false;
                break;
            }
        
        //evaluations
        $evaluation = DB::table('evaluations')
                           ->where('opportunity_id', $opportunity->id)
                           ->first();
        $etat_evaluation = (!empty($evaluation)) ? true : false;

        if($opportunity->isScheduled)
            return view('livrables.calendar-start')
            ->with('livrables', $livrables)
            ->with('opportunity', $opportunity)
            ->with('status_mission', $mission_status)
            ->with('etat_formulaire', $etat_formulaire)
            ->with('evaluation', $evaluation)
            ->with('etat_evaluation', $etat_evaluation);

        return view('livrables.index')
            ->with('livrables', $livrables)
            ->with('opportunity', $opportunity)
            ->with('sum_days_livrable', $sum_days_livrable)
            ->with('etat_evaluation', $etat_evaluation);

    }

    public function details_livrable($id)
    {
        /** @var Opportunity $opportunity */
        $opportunity = Opportunity::find($id);
        if (empty($opportunity)) {
            Flash::error('Opportunité non trouvée !');
            return redirect(route('opportunities.index'));
        }

        //Client
        $client = Client::find($opportunity->client_id);
        if (empty($client)) {
            Flash::error('Le client relatif à cette opportunité n\'est plus trouvé !');
            return redirect(route('home'));
        }

        //Members
        $members = Member::where('client_id', $client->id)->get();
        
        //Livrables
        $etat_formulaire = true;
        $livrables = DB::table('livrables')->where('opportunity_id', $opportunity->id)->WhereNull('deleted_at')->get();
        $etat_formulaire = (empty($livrables)) ? false : true;
        foreach ($livrables as $livrable) 
            if($livrable->statut != 2){
                $etat_formulaire = false;
                break;
            }
        
        return view('missions.calendrier', compact('opportunity', 'client', 'livrables', 'members', 'etat_formulaire'));
    }

    public function soummetre(Request $request, $id)
    {
        $livrable = Livrable::findOrFail($id);

        $data = $request->all();

        $user = Auth::user();
        $opportunity = Opportunity::where('id', $livrable->opportunity_id)->first();

        if (!$opportunity->launched) {
            Flash::error('La mission doit etre lance au prealable par le createur de la mission !');
            return redirect()->back();
        }

        //Livrable & files
        $this->validate($request, [
            'execution_file_id' => 'mimes:doc,pdf,docx,xls,xlsx,ppt,pptx,txt'
        ]);

        if($request->hasfile('execution_file_id'))
        {
            $filePath = 'opportunities/soumissions';
            $file = $request->file('execution_file_id');
            $extension = $file->getClientOriginalExtension();
            do {
                $data['execution_file_id'] = Str::random(20). '.' . $extension;
                $file_state = File::where('id', $data['execution_file_id']);
                File::firstOrCreate(
                    [
                        'id' => $data['execution_file_id']
                    ],
                    [
                        'id' => $data['execution_file_id'],
                        'type' => $extension
                    ]
                );
            } while (empty($file_state));

            $file->storeAs($filePath, $data['execution_file_id'], 's3');            
        }
        $livrable->execution_file_id = $data['execution_file_id'];
        $livrable->statut = 1;
        $livrable->save();


        $user = Auth::user();

        //Livrables
        $livrables = Livrable::where('opportunity_id', $opportunity->id)->get();
        $etat_formulaire = true;
        $etat_formulaire = (empty($livrables)) ? false : true;
        foreach ($livrables as $livrable) 
            if($livrable->statut != 2){
                $etat_formulaire = false;
                break;
            }

        $admin_user = User::find($opportunity->author_id);
        
        Mail::to($admin_user->email)->send(new Soumettre($user, $opportunity, $livrable));

        Flash::success('Votre livrable a été envoyé avec succes !');
        return redirect()->back();
    }

    public function valider(Request $request, $id)
    {
        $livrable = Livrable::findOrFail($id);

        $data = $request->all();

        $livrable->statut = ( $data['state_validation'] ) ? 2 : 3 ;
        $livrable->save();

        $opportunity = Opportunity::where('id', $livrable->opportunity_id)->first();
        $mission = Mission::where('opportunity_id', $opportunity->id)->first();
        $user = User::find($mission->user_id);
        $user_admin = User::find($opportunity->author_id);

        //Livrables
        $livrables = Livrable::where('opportunity_id', $opportunity->id)->get();
        $etat_formulaire = true;
        $etat_formulaire = (empty($livrables)) ? false : true;
        foreach ($livrables as $livrable) 
            if($livrable->statut != 2){
                $etat_formulaire = false;
                break;
            }

        Mail::to($user->email)->send(new AccepterRefuser($user, $opportunity, $livrable));
        Flash::success('Votre action a été appliqué avec succés !');
        return redirect()->back();
    }

    public function validation(Request $request)
    {
        $data = $request->all();

        $mission = Mission::where('opportunity_id', $data['id'])->first();
        $opportunity = Opportunity::findOrFail($data['id']);

        //Evaluation 
        $this->validate($request, [
            'note_atteinte_objectifs' => 'min:0|max:5',
            'note_respect_delais' => 'min:0|max:5',
            'note_qualite_livrable' => 'min:0|max:5'
        ]);

        $data['note'] = intval(($data['note_atteinte_objectifs'] + $data['note_respect_delais'] + $data['note_qualite_livrable']) / 3);

        //Stepping up on the register
        $evaluation_id = DB::table('evaluations')->insertGetId([
            'avis' => $data['avis'],
            'note_atteinte_objectifs' => $data['note_atteinte_objectifs'],
            'note_respect_delais' => $data['note_respect_delais'],
            'note_qualite_livrable' => $data['note_qualite_livrable'],
            'note' => $data['note'],
            'opportunity_id' => $data['id']
        ]);

        $evaluation = DB::table('evaluations')
                      ->where('id', $evaluation_id)
                      ->first();

        $admin_user = User::find($opportunity->author_id);
        $coach_user = User::find($mission->user_id);
        
        // Validation effectue pour le coach/administrateur
        Mail::to($coach_user->email)->send(new ClotureMission($coach_user, $opportunity, $mission, $evaluation));
        Flash::success('Evaluation éffectué avec succes !');
        return redirect(route('livrable.index', [$opportunity->id]));
    }

    /**
     * Show the form for creating a new Livrable.
     *
     * @return Response
     */
    public function create()
    {
        return view('livrables.create');
    }

    public function create_override($id)
    {
        /** @var Opportunity $opportunity */
        $opportunity = Opportunity::find($id);
        if (empty($opportunity)) {
            Flash::error('Opportunité non trouvée !');
            return redirect(route('opportunities.index'));
        }
        return view('livrables.create', compact('opportunity'));
    }

    /**
     * Store a newly created Livrable in storage.
     *
     * @param CreateLivrableRequest $request
     *
     * @return Response
     */
    public function store(CreateLivrableRequest $request)
    {
        $data = $request->all();

        /** @var Opportunity $opportunity */
        $opportunity = Opportunity::find($data['opportunity_id']);
        if (empty($opportunity)) {
            Flash::error('Opportunité non trouvée !');
            return redirect(route('opportunities.index'));

resources/views/livrables/calendar-start.blade.php
@extends('layouts.app')

@section('content')
@php
    $note = isset($evaluation->note) ? $evaluation->note : null;
@endphp
    <div class="content-home">
        
        <div class="nav-item nav-item-title">
            <p class="title">&nbsp;&nbsp;Calendrier d'execution </p>
            @if($note)
            &nbsp;&nbsp; Note : <b><small style="color: green"> {{$note}} / 5 </small></b>
            @endif
        </div>

        <div class="body-home">
            <div class="block-one">
                <div class="content-table content-table-2">

                    <div class="content px-3">

                        @include('flash::message')
                
                        <div class="clearfix"></div>
                
                        <div class="card">
                            <div class="card-body p-0">
                                @include('livrables.table')
                
                                <div class="card-footer clearfix">
                                    <div class="float-right">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                
                    </div>

                    <div class="block-empty-element">
                        @if(!$opportunity->launched && $opportunity->author_id == Auth::id())
                            @if($status_mission)
                                {!! Form::open(['route' => 'livrable.launch']) !!}
                                    {!! Form::hidden('id', $opportunity->id ) !!}
                                    <p class="empty-text">Votre mission n'est toujours pas lance !</p>
                                    {!! Form::submit('Let\'s launch it ', ['type' => 'submit', 'class' => 'btn btn-envoie bg-orange', 'onclick' => "return confirm('Do you want to launch this mission ?')"]) !!}
                                {!! Form::close() !!}
                            @endif
                        @elseif($etat_evaluation)
                            <p class="statut-accepte" style="border: 2px solid green ; color: green ">Cloturé</p>
                        @elseif($etat_formulaire && $opportunity->author_id == Auth::id() && !$etat_evaluation )
                            <br>
                            <a href="{{route('mission.evaluation', [$opportunity->id])}}" class="btn btn-envoie bg-success"> Cloturer cette mission !</a>

                            {{-- <div class="col-sm-6">
                                <h5 style="color: rgba(178, 140, 63, 0.782);"> ** Formulaire d'evaluation **</h5>
                            </div>
                            <br>
                            </center>
                                {!! Form::open(['route' => 'livrable.validation']) !!}
                                    {!! Form::hidden('id', $opportunity->id ) !!}
                                    <div class="form-group col-sm-6">
                                        {!! Form::label('avis', 'Qu\'avez vous pense de la prestation de ce coach ? ') !!}
                                        {!! Form::textarea('avis', null, ['class' => 'form-control', 'required' => 'required']) !!}
                                    </div>

                                    <div class="form-group col-sm-6">
                                        {!! Form::label('note', 'Quel note allez vous attribue ( / 5 ) ?') !!}
                                        {!! Form::number('note', null, ['class' => 'form-control', 'required' => 'required']) !!}
                                    </div>

                                    <div class="form-group col-sm-6">
                                        {!! Form::submit('Envoyer le formulaire d\'évaluation ', ['type' => 'submit', 'class' => 'btn bg-orange', 'onclick' => "return confirm('Do you want to close this mission ?')"]) !!}
                                    </div>
                                {!! Form::close() !!}
                            </center> --}}
                        @elseif($opportunity->launched)
                            <a href="#" class="btn btn-envoie bg-success"> Launched !</a>
                        @endif
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="modal fade" id="valid-evaluation" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ajouter un livrable pour la mission</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="form1">
                        <div class="group-input-log">
                            <label for="" class="form-label">Libellé de la phase </label>
                            <input type="text" placeholder="Entrer le" class="form-control" id="" >
                        </div>
                        <div class="group-input-log">
                            <label for="" class="form-label">Email</label>
                            <input type="email" placeholder="example@domain.com" class="form-control" id="" >
                        </div>
                        <div class="modal-footer-custom">
                            <a href="" class="btn btn-tdr btn-orange" >Assigner l'opportunité</a>
                            <a href="" class="btn btn-tdr btn-danger" >Retour au Dashboard</a>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

@stop

resources/views/livrables/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Livrable</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'livrables.store', 'files' => true]) !!}

            <div class="card-body">

                <div class="row">
                    @include('livrables.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('livrable.index', [ $opportunity->id]) }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/livrables/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Livrable</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($livrable, ['route' => ['livrables.update', $livrable->id], 'method' => 'patch', 'files' => true]) !!}

            <div class="card-body">
                <div class="row">
                    @include('livrables.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('livrable.index', [$opportunity->id]) }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/livrables/fields.blade.php
<!-- Libelle Field -->
<div class="form-group col-sm-6">
    {!! Form::label('libelle', 'Libelle du livrable :') !!}
    {!! Form::text('libelle', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<!-- Deadline Field -->
<div class="form-group col-sm-6">
    {!! Form::label('deadline', 'Nombre maximun de jours du livrable :') !!}
    {!! Form::number('deadline', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<!-- Template file id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('template_file_id', 'Template du livrable :') !!}
    <div class="input-group">
        <div class="custom-file">
            {!! Form::file('template_file_id', ['class' => 'custom-file-input']) !!}
            {!! Form::label('template_file_id', 'Choose file', ['class' => 'custom-file-label', 'required' => 'required']) !!}
        </div>
    </div>
</div>

{!! Form::hidden('opportunity_id', $opportunity->id) !!}
<div class="clearfix"></div>

resources/views/livrables/table.blade.php
@php
    $user = Auth::user();
@endphp
<div class="table-responsive">
    <table class="table" id="livrables-table">
        <thead>
        <tr>
            <th>Libelle</th>
            <th>Deadline</th>
            <th>Template</th>
            <th>Soumission</th>
            <th colspan="3">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($livrables as $livrable)
            @php
            $template = ($livrable->template_file_id) ? Storage::disk('s3')->temporaryUrl('opportunities/livrables/'. $livrable->template_file_id, now()->addMinutes(30)) : null;
            $soumission = ($livrable->execution_file_id) ? Storage::disk('s3')->temporaryUrl('opportunities/soumissions/'. $livrable->execution_file_id, now()->addMinutes(30)) : null;
            @endphp
            <tr>
                <td>&nbsp;&nbsp;&nbsp;{{ $livrable->libelle }}</td>
                <td>{{ $livrable->deadline }} jours</td>
                <td>
                    @if($template)
                        <a href="{{ $template }}" class='btn btn-success btn-xs'  target="_blank">Voir template</a>
                    @else
                        <span class='btn btn-default btn-xs' style="background-color: rgba(234, 236, 239, 0.782);">No file found !</span>
                    @endif
                </td>
                @if(!$livrable->statut)
                    <td><p class="statut-accepte" style="border: 2px solid gray; color: gray">Soumission en attente ...</p></td>
                @elseif($livrable->statut == 1)
                    <td><p class="statut-accepte" style="border: 2px solid rgba(231, 185, 91, 0.96) "><a href="{{ $soumission }}" style="color: rgba(231, 185, 91, 0.772); text-decoration: none" target="_blank">Voir soumission</a></p></td> 
                @elseif($livrable->statut == 2)
                    <td><p class="statut-accepte" style="border: 2px solid green "><a href="{{ $soumission }}" style="color: green; text-decoration: none" target="_blank" data-toggle="tooltip" data-placement="top" title="Cliquer pour revoir soumission !">Accepté</a></p></td> 
                @elseif($livrable->statut == 3)
                    <td><p class="statut-accepte" style="border: 2px solid red "><a href="{{ $soumission }}" style="color: red; text-decoration: none" target="_blank" data-toggle="tooltip" data-placement="top" title="Cliquer pour revoir soumission !">Refusé !</a></p></td> 
                @endif

                @if(!$opportunity->isScheduled && $opportunity->author_id == $user->id)              
                    <td width="120">
                        {!! Form::open(['route' => ['livrables.destroy', $livrable->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                            <a href="{{ route('livrables.edit', [$livrable->id]) }}"
                            class='btn btn-default btn-xs'>
                                <i class="far fa-edit"></i>
                            </a>
                            {!! Form::button('<i class="far fa-trash-alt"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                    </td>
                @else
                    @if($opportunity->author_id == Auth::id() && $livrable->statut && $template && !$etat_evaluation && $opportunity->author_id == $user->id)
                    <td width="120">
                        {!! Form::open(['route' => ['livrable.valider', $livrable->id], 'method' => 'post']) !!}
                        <div class='btn-group'>
                            <button type="submit" value="1" name='state_validation' class="btn btn-success btn-xs" onclick="return confirm('Etes vous sure de valider ce livrable ?')"><i class="fa fa-check"></i></button>
                            <button type="submit" value="0" name='state_validation' class="btn btn-danger btn-xs"  onclick="return confirm('Etes vous sure de rejeter ce livrable ?')"> <b>X</b> </button>
                        </div>
                        {!! Form::close() !!}
                    </td>
                    @endif 
                @endif
            </tr>
        @endforeach
        </tbody>
    </table>
</div>