routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('send-mail', function () {

    $details = [
        'title' => 'Mail from Lufa Intégrateur',
        'body' => 'This is for testing email using mailjet'
    ];

    \Mail::to('mokhouthioune96@gmail.com')->send(new \App\Mail\MyTestMail($details));

    dd("Email is Sent.");
});

Auth::routes();

Route::get('/', function () {
    //return View::make('welcome');
    return View::make('auth.login');
})->name('welcome');

Route::post('/login', [App\Http\Controllers\Auth\LoginController::class, 'override_login'])->name('override.login');
Route::post('/register', [App\Http\Controllers\Auth\RegisterController::class, 'override_register'])->name('override.register');
Route::post('/register/step', [App\Http\Controllers\Auth\RegisterController::class, 'register_step'])->name('register.step');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->middleware('auth')->name('home');
Route::get('/home-admin', [App\Http\Controllers\HomeController::class, 'homeAdmin'])->middleware('auth')->middleware('cabinet')->name('homeAdmin');

Route::resource('users', App\Http\Controllers\UserController::class)->middleware('isAdmin')->middleware('auth');
Route::get('/user/detail/{id}', [App\Http\Controllers\UserController::class, 'show_override'])->middleware('isAdmin')->middleware('auth')->name('users.detail');
Route::get('/user/profiling/{id}', [App\Http\Controllers\UserController::class, 'profiling'])->middleware('isAdmin')->middleware('auth')->name('users.profiling');
Route::post('/user/notation', [App\Http\Controllers\UserController::class, 'notation'])->middleware('isAdmin')->middleware('auth')->name('users.notation');

Route::resource('roles', App\Http\Controllers\RoleController::class)->middleware('isAdmin')->middleware('auth');
Route::resource('addresses', App\Http\Controllers\AddressController::class)->middleware('isAdmin')->middleware('auth');
Route::resource('transactions', App\Http\Controllers\TransactionController::class)->middleware('isAdmin')->middleware('auth');
Route::resource('clients', App\Http\Controllers\ClientController::class)->middleware('isAdmin')->middleware('auth');

Route::resource('members', App\Http\Controllers\MemberController::class)->middleware('auth');
Route::get('/member/{id}', [App\Http\Controllers\MemberController::class, 'indexOth'])->middleware('isAdmin')->middleware('auth')->name('members.team.index');
Route::get('/member/create/{id}', [App\Http\Controllers\MemberController::class, 'createOth'])->middleware('isAdmin')->middleware('auth')->name('members.team.create');

Route::resource('opportunities', App\Http\Controllers\OpportunityController::class)->middleware('cabinet')->middleware('auth');
Route::get('/opportunities/share/{id}', [App\Http\Controllers\OpportunityController::class, 'share'])->middleware('cabinet')->middleware('auth')->name('opportunities.share');
Route::post('/opportunities/scheduled', [App\Http\Controllers\OpportunityController::class, 'isScheduled'])->middleware('cabinet')->middleware('auth')->name('opportunities.scheduled');

Route::resource('missions', App\Http\Controllers\MissionController::class)->middleware('cabinet')->middleware('auth');
Route::post('missions/store/coach', [App\Http\Controllers\MissionController::class, 'store_coach'])->middleware('auth')->name('missions.store.coach');
Route::get('missions/details/{id}', [App\Http\Controllers\MissionController::class, 'show_override'])->middleware('auth')->name('missions.details');
Route::get('evaluation/{id}', [App\Http\Controllers\MissionController::class, 'evaluation'])->middleware('cabinet')->middleware('auth')->name('mission.evaluation');

Route::resource('livrables', App\Http\Controllers\LivrableController::class);
Route::get('livrables/mission/{id}', [App\Http\Controllers\LivrableController::class, 'index_override'])->middleware('auth')->name('livrable.index');
Route::get('livrable/{id}', [App\Http\Controllers\LivrableController::class, 'create_override'])->middleware('auth')->name('livrable.create');
Route::post('launch/livrable', [App\Http\Controllers\LivrableController::class, 'launch'])->middleware('auth')->middleware('cabinet')->name('livrable.launch');
Route::get('details_livrable/{id}', [App\Http\Controllers\LivrableController::class, 'details_livrable'])->middleware('auth')->name('details_livrable');
Route::patch('soummetre/livrable/{id}', [App\Http\Controllers\LivrableController::class, 'soummetre'])->middleware('auth')->name('livrable.soummetre');
Route::post('valider/livrable/{id}', [App\Http\Controllers\LivrableController::class, 'valider'])->middleware('cabinet')->middleware('auth')->name('livrable.valider');
Route::post('validation/livrable', [App\Http\Controllers\LivrableController::class, 'validation'])->middleware('cabinet')->middleware('auth')->name('livrable.validation');

Route::get('messages', [App\Http\Controllers\ContactController::class, 'mes_messages'])->middleware('auth')->name('messages.index');
Route::post('store_messages', [App\Http\Controllers\ContactController::class, 'store_messages'])->middleware('auth')->name('store_messages');
Route::get('messages/{id}', [App\Http\Controllers\ContactController::class, 'show_messages'])->middleware('auth')->name('messages.show');

Route::get('/calendrier-mission', function () {
    return View::make('missions.calendrier');
});

Route::get('/admin/calendrier-excution-empty', function () {
    return View::make('livrables.calendrier-add');
});
Route::get('/admin/calendrier-excution', function () {
    return View::make('admin.calendrier-excution');
});

Route::get('/register/step/5', function () {
    return View::make('auth.register-step-5');
});

// Route::get('/admin/gestion-opportinute', function () {
//     return View::make('admin.gestion-opportinute');
// });
// Route::get('/admin/creer-une-opportinute', function () {
//     return View::make('admin.creer-une-opportinute');
// });
// Route::get('/admin/attribution-opportunite', function () {
//     return View::make('admin.attribution-opportunite');
// });

// Route::resource('files', App\Http\Controllers\FileController::class);
// Route::resource('categories', App\Http\Controllers\CategoryController::class);
// Route::resource('categorieCoaches', App\Http\Controllers\CategorieCoachController::class);

app/Models/Mission.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class Mission
 * @package App\Models
 * @version July 16, 2023, 10:06 pm UTC
 *
 * @property string $state
 * @property string $stepping
 * @property string $reason
 * @property unsignedInteger $opportunity_id
 * @property unsignedInteger $user_id
 */
class Mission extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'missions';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'status',
        'stepping',
        'reason',
        'opportunity_id',
        'user_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'status' => 'string',
        'stepping' => 'string',
        'reason' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'opportunity_id' => 'required',
        'user_id' => 'required'
    ];

    
}

app/Http/Controllers/MissionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMissionRequest;
use App\Http\Requests\UpdateMissionRequest;
use App\Http\Controllers\AppBaseController;
use App\Models\Mission;
use App\Models\Opportunity;
use App\Models\Client;
use Illuminate\Http\Request;
use Flash;
use Response;  
use DB;

class MissionController extends AppBaseController
{
    /**
     * Display a listing of the Mission.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        /** @var Mission $missions */
        $missions = Mission::all();

        return view('missions.index')
            ->with('missions', $missions);
    }

    /**
     * Show the form for creating a new Mission.
     *
     * @return Response
     */
    public function create()
    {
        return view('missions.create');
    }

    /**
     * Store a newly created Mission in storage.
     *
     * @param CreateMissionRequest $request
     *
     * @return Response
     */
    public function store(CreateMissionRequest $request)
    {
        $input = $request->all();

        /** @var Mission $mission */
        $mission = Mission::firstOrCreate(
            [
                'opportunity_id' =>  $input['opportunity_id'],
            ],
            [
                'opportunity_id' =>  $input['opportunity_id'],
                'user_id' =>  $input['user_id']
            ],
        );

        Flash::success('Mission enregistré avec succès.');

        return redirect(route('opportunities.index'));
    }

    public function store_coach(Request $request){
        /** @var Mission $mission */
        $input = $request->all();
        $mission = Mission::find($input['id']);

        if (empty($mission)) {
            Flash::error('Mission introuvable !');
            return redirect(route('home'));
        }

        if(isset($input['accepted'])){
            $input['status'] = 'Accepté';
        }else if(isset($input['refused'])){
            $input['status'] = 'Refusé';
            $mission->delete();
        }
        $mission->fill($input);
        $mission->save();

        Flash::success('Mission accepté avec succès');

        return redirect(route('home'));

    }

    /**
     * Display the specified Mission.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var Mission $mission */
        $mission = Mission::find($id);

        if (empty($mission)) {
            Flash::error('Mission introuvable !');

            return redirect(route('missions.index'));
        }

        return view('missions.show')->with('mission', $mission);
    }

    public function show_override($id)  
    {
        /** @var Mission $mission */
        $mission_initial = Mission::find($id);

        if (empty($mission_initial)) {
            Flash::error('Mission introuvable !');
            return redirect(route('home'));
        }

        $opportunity = Opportunity::find($mission_initial->opportunity_id);
        if (empty($opportunity)) {
            Flash::error('L\'opportunité n\'est plus retrouvée');
            return redirect(route('home'));
        }

        $client = Client::find($opportunity->client_id);
        if (empty($client)) {
            Flash::error('Le client relatif à cette opportunité n\'est plus trouvé !');
            return redirect(route('home'));
        }

        $mission = DB::table('opportunities')
        ->select('opportunities.*', 'missions.id as mission_id', 'missions.status', 'missions.user_id', 'missions.reason')
        ->join('missions', 'missions.opportunity_id', 'opportunities.id')
        ->whereNull('missions.deleted_at')
        ->where('missions.id', $mission_initial->id)
        ->first();

        /* Opportunities - categories */
        $categories = DB::table('opportunity_categories')
        ->select('categories.libelle')
        ->join('categories', 'opportunity_categories.category_id', 'categories.id')
        ->where('opportunity_id', $opportunity->id)
        ->get();

        /* Opportunities - attachments */
        $attachments = DB::table('attachments')
        ->select('attachments.id', 'attachments.libelle', 'attachments.type')
        ->where('opportunity_id', $opportunity->id)
        ->orderBy('created_at', 'ASC')
        ->get();

        return view('missions.details')
            ->with('mission', $mission)
            ->with('client', $client)
            ->with('categories', $categories)
            ->with('attachments', $attachments);

    }

    // Evaluation end of mission with notation
    public function evaluation($id)
    {
        /** @var Opportunity $opportunity */
        $opportunity = Opportunity::find($id);

        if (empty($opportunity)) {
            Flash::error('Opportunite introuvable !');
            return redirect(route('opportunities.index'));
        }

        //Etat formulaire
        $etat_formulaire = true;
        $livrables = DB::table('livrables')->where('opportunity_id', $opportunity->id)->WhereNull('deleted_at')->get();
        $etat_formulaire = (empty($livrables)) ? false : true;
        if(!$etat_formulaire)
            return redirect(route('livrable.index', [$opportunity->id]));
        foreach ($livrables as $livrable) 
            if($livrable->statut != 2)
                return redirect(route('livrable.index', [$opportunity->id]));
            
        return view('missions.evaluation')->with('opportunity', $opportunity);
    }

    /**
     * Show the form for editing the specified Mission.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        /** @var Mission $mission */
        $mission = Mission::find($id);

        if (empty($mission)) {
            Flash::error('Mission introuvable !');

            return redirect(route('missions.index'));
        }

        return view('missions.edit')->with('mission', $mission);
    }

    /**
     * Update the specified Mission in storage.
     *
     * @param int $id
     * @param UpdateMissionRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMissionRequest $request)
    {
        /** @var Mission $mission */
        $mission = Mission::find($id);

        if (empty($mission)) {
            Flash::error('Mission introuvable !');

            return redirect(route('missions.index'));
        }

        $mission->fill($request->all());
        $mission->save();

        Flash::success('Mission a été mis a jour avec succès.');

        return redirect(route('missions.index'));
    }

    /**
     * Remove the specified Mission from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var Mission $mission */
        $mission = Mission::find($id);

        if (empty($mission)) {
            Flash::error('Mission introuvable !');

            return redirect(route('missions.index'));
        }

        $mission->delete();

        Flash::success('Mission a été supprimé avec succès.');

        return redirect(route('opportunities.index'));
    }
}

resources/views/missions/calendrier.blade.php
@extends('layout.default')
@php
    $count_members = (!empty($members)) ? count($members) : 0;
@endphp
@section('content')

    <div class="content-home">
        @section('content-header')
        <li class="nav-item nav-item-title">
            <p class="title">Suivi de la mission : {{$opportunity->libelle}} - {{$client->company_name}} </p>
        </li>
        @stop
        
        <div class="body-home">
            <div class="block-one">
                <div class="head-table d-flex justify-content-between align-items-center">
                    <p>Calendrier d'execution de la mission</p><br>
                </div>
                <div class="content-table content-table-2">
                    @include('flash::message')
                    <table class="table table-responsive">
                        <thead>
                        <tr>
                            <th scope="col">Livrable </th>
                            <th scope="col">Deadline</th>
                            <th scope="col">Validation (1er)</th>
                            <th scope="col">Options</th>
                        </tr>
                        </thead>
                        <tbody>
                           @foreach($livrables as $livrable)
                           @if($livrable)
                           @php 
                               $deadline = ($opportunity->launched) ? strtotime($opportunity->launched) : strtotime($opportunity->deadline);   
                               $dateDepart = Carbon\Carbon::parse(date('d-m-Y', $deadline)); 
                               $dateApresAjout = $dateDepart->addDays($livrable->deadline);

                               $template = ($livrable->template_file_id) ? Storage::disk('s3')->temporaryUrl('opportunities/livrables/'. $livrable->template_file_id, now()->addMinutes(30)) : null;
                           @endphp
                        <tr>
                            <td>{{$livrable->libelle}}</td>
                            <td>{{date('d-m-Y', strtotime($dateApresAjout))}}</td>
                            
                            @if($livrable->statut == 0)
                                <td><p class="statut-accepte" style="border: 2px solid gray; color: gray">Soumission en attente ...</p></td>
                            @elseif($livrable->statut == 1)
                                <td><p class="btn btn-envoie bg-orange" style="color: white">En cours d'examen</p></td>
                            @elseif($livrable->statut == 2)
                                <td><p class="btn btn-envoie btn-success" style="color: white">Validé</p></td>
                            @elseif($livrable->statut == 3)
                                <td><p class="btn btn-envoie btn-danger" style="color: white">Refusé</p></td>
                            @endif
                            <td style="display:flex;">
                            <a class="statut-accepte" style="border: 2px solid rgba(205, 78, 68, 0.782); color: rgba(205, 78, 68, 0.782); text-decoration: none" href="{{ $template }}" target="_blank">Download <i class="fa fa-download"></i></a><br><br>
                            
                            @if(($livrable->statut == 0 || $livrable->statut == 3) && $opportunity->launched)
                            <form action="{{route('livrable.soummetre', $livrable->id)}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PATCH')
                                <button type="submit" class="statut-accepte" style="border: 2px solid rgba(52, 118, 37, 0.782); color: rgba(52, 118, 37, 0.782); text-decoration: none" >Soumettre <i class="fa fa-upload"></i></button>
                                <input type="file" class="custom-file-label" name="execution_file_id" id="" required>
                                @error('execution_file_id')
                                <span class="error invalid-feedback">{{ $message }}</span>
                                @enderror
                            </form>
                            @endif

                            @if(!$opportunity->launched)
                                <small style="color: rgba(205, 78, 68, 0.782);">Mission pas encore lancé par le createur !</small>
                            @endif 
                            <!--
                            <div class="dropdown">
                                <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img class="img-options" src="{{asset('img/options.png')}}" alt="">
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item" href="#">Action</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                </ul>
                            </div> 
                            -->
                            </td>
                        </tr>
                        @endif
                        @endforeach
                       
                       
                        </tbody>
                    </table>
                </div>
            </div>

            <div>
                <div class="head-table d-flex justify-content-between align-items-center">
                    <p>{{ $client->company_name }}</p>
                    {{-- <button type="button" data-bs-toggle="modal" data-bs-target="#Modaladdmember" class="btn btn-envoie bg-orange"> <img src="{{asset('img/add.svg')}}" alt="">Ajouter un membre</button> --}}
                </div>
                @if($count_members)
                <div class="content-table content-table-2">
                    <table class="table table-responsive">
                        <thead>
                        <tr>
                            {{-- <th scope="col">Nom du client</th> --}}
                            <th scope="col">Nom et Prénom</th>
                            <th scope="col">Fonction</th>
                            <th scope="col">Adresse Email </th>
                            {{-- <th scope="col">Options</th> --}}
                        </tr>
                        </thead>
                        <tbody>

                        @foreach ($members as $member)
                            
                            <tr>
                                {{-- <td>GIZ Sénégal </td> --}}
                                <td>{{$member->nom}}</td>
                                <td>{{$member->fonction}}</td>
                                <td>{{$member->email}}</td>
                                {{-- 
                                <td class="d-flex" >
                                    <button type="button" class="btn btn-options">
                                        <img  src="{{asset('img/remove.svg')}}" alt="">
                                    </button>
                                    <button type="button" class="btn btn-options">
                                        <img  src="{{asset('img/add-circle.svg')}}" alt="">
                                    </button>
                                </td> --}}
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                @endif
            </div>

        </div>
    </div>



    <!-- Modal envoie formular -->
    <div class="modal fade" id="modalSendFormular" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <img class="img-form" src="{{asset('img/formular.png')}}" alt="">
                    <p class="title-modal-check">Le formulaire d'évaluation a été envoyé avec succés </p>
                    <p class="description-modal-check">Les membres du cabinet conseil que vous avez invité y auront accès et se chargeront de vous évaluer</p>
                </div>
                <div class="modal-footer-custom">
                    <a href="" class="btn btn-tdr btn-orange" >Consulter le calendrier</a>
                    <a href="" class="btn btn-tdr btn-danger" >Retour au Dashboard</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="Modaladdmember" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ajouter un membre | Cabinet Conseil</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <form action="{{ route('members.store') }}" method="POST">
                        <div class="form1">
                            @csrf
                            <input type="hidden" name="client_id" value="{{ $client->id }}">
                            <input type="hidden" name="perspective_coach" value="1">
                            <input type="hidden" name="opportunity_id" value="{{ $opportunity->id }}"> 
                            <div class="group-input-log">
                                <label for="" class="form-label">Prénom</label>
                                <input type="text" name="prenom" class="form-control" id="" >
                            </div>
                            <div class="group-input-log">
                                <label for="" class="form-label">Nom </label>
                                <input type="text" name="nom" class="form-control" id="" >
                            </div>
                            <div class="group-input-log">
                                <label for="" class="form-label">Email</label>
                                <input type="email" name="email" class="form-control" id="" >
                            </div>
                            <div class="group-input-log">
                                <label for="" class="form-label">Fonction</label>
                                <input type="text" name="fonction" class="form-control" id="" >
                            </div>
                            <button type="submit" id="" class="btn stepButton btn-valider-log">Valider</button>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>



@stop

resources/views/missions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Create Mission</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'missions.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('missions.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('missions.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/missions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>Edit Mission</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($mission, ['route' => ['missions.update', $mission->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('missions.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('missions.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/missions/fields.blade.php
<!-- State Field -->
<div class="form-group col-sm-6">
    {!! Form::label('state', 'State:') !!}
    {!! Form::text('state', null, ['class' => 'form-control']) !!}
</div>

<!-- Stepping Field -->
<div class="form-group col-sm-6">
    {!! Form::label('stepping', 'Stepping:') !!}
    {!! Form::text('stepping', null, ['class' => 'form-control']) !!}
</div>

<!-- Reason Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('reason', 'Reason:') !!}
    {!! Form::textarea('reason', null, ['class' => 'form-control']) !!}
</div>

resources/views/missions/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Missions</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('missions.create') }}">
                        Add New
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            <div class="card-body p-0">
                @include('missions.table')

                <div class="card-footer clearfix">
                    <div class="float-right">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/missions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mission Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('missions.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('missions.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/missions/show_fields.blade.php
<!-- State Field -->
<div class="col-sm-12">
    {!! Form::label('state', 'State:') !!}
    <p>{{ $mission->state }}</p>
</div>

<!-- Stepping Field -->
<div class="col-sm-12">
    {!! Form::label('stepping', 'Stepping:') !!}
    <p>{{ $mission->stepping }}</p>
</div>

<!-- Reason Field -->
<div class="col-sm-12">
    {!! Form::label('reason', 'Reason:') !!}
    <p>{{ $mission->reason }}</p>
</div>

<!-- Opportunity Id Field -->
<div class="col-sm-12">
    {!! Form::label('opportunity_id', 'Opportunity Id:') !!}
    <p>{{ $mission->opportunity_id }}</p>
</div>

<!-- User Id Field -->
<div class="col-sm-12">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{{ $mission->user_id }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $mission->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $mission->updated_at }}</p>
</div>